### ISSUE TITLE
Can I use Https to init submodule?

### ISSUE THREAD

**Issue by JavaCS3** [YoeDistro/yoe-distro#146]
My company firewall doesn't allow us to connect to Github via SSH directly. How can I replace all SSH connection to HTTPS?

**Comment by cbrake** [comment]
so looking at https://github.com/YoeDistro/yoe-distro/blob/master/.gitmodules, it appears we are using the git protocol for most of the submodules (appears there are 3 git protocols https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols). I would support changing all the git URLs in .gitmodules to use the https instead of the git protocol, as that is likely most compatible with company firewalls.

Thoughts @kraj ?

**Comment by kraj** [comment]
@cbrake yes we used git but I would prefer https myself too. Care for a patch ?
 :)

**Comment by JavaCS3** [comment]
Thanks
